title: DCRYAN'S BLOG
description: DCRYAN'S BLOG

url: dcryan.com
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
gems: [jekyll-paginate]
paginate: 5

navigation:
 - title: 主页
   url: /index.html
 - title: 文章
   url: /articles
 - title: 分类
   url: /categories
 - title: 关于
   url: /about

social:
   github: halcity
   linkedin: 
   facebook: 
   email: im@napolin.cn

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      comments: false
